version: '3'

services:
  client:
    build: ./client
    restart: always
    environment:
      REACT_APP_BASE_URL:  "http://localhost:5555/todos"
    ports:
      - '3333:3000'
    volumes:
      - /app/node_modules
      - ./client:/app
  server:
    build: ./server
    restart: always
    environment:
      MYSQL_HOST:  mysql
      MYSQL_USER: root
      MYSQL_PORT: '3306'
      MYSQL_PASSWORD: '123456'
      MYSQL_DB: devops_p1
    ports: 
      - '5555:5000'
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - /app/env
      - ./server:/app
  mysql: 
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: devops_p1
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080' 

volumes:
  mysql_data:
  
